### PR TITLE
comparisons: add RestrictedAny family of classes, analogous to mock.ANY 

### PR DESCRIPTION
**Pull request by risicle**
Need I say more?

I need to use these in more tests I'm writing, so would like to get this in soon.

### CODE REVIEW

**Comment by risicle** [comment]
Although the more I think about this, "malleable" may not be the right word here because actually this class is more *restricted* than `mock.ANY`. I wonder if `RestrictedAny` would be a better name?

**Comment by risicle** [comment]
Moved this to `comparisons.py`, renamed to `RestrictedAny`.

**Comment by galund** [comment]
Why override `__repr__` in these?

**Comment by galund** [comment]
Oh don't worry, I get it...

... I think these just need something in the name (or in the module name) showing that they are mocks. Maybe we could have `dmutils.mock.comparisons`?

**Comment by risicle** [comment]
Well, they're not *really* mocks, are they? `mock.ANY` happens to live in `mock` because it has a use there (presumably originally matching recorded arguments of calls).

**Comment by galund** [comment]
Yep ok point taken.

Are we expecting tests for these? Tests would probably be enough the make the expected usage/use cases clear.

**Comment by katstevens** [comment]
(If not tests, then example usage in the docstrings, maybe?)

**Comment by risicle** [comment]
Tests? Perhaps if they got more complicated. Would be the first tests for this repo and would probably involve giving it a `requirements-dev.txt` and all that faff. Which also raises the question - all these undeclared dependencies we have because of the decision to try and avoid diamond dependencies - do we now have to declare them all in `requirements-dev.txt`...? Luckily this feature itself doesn't have any dependencies.

Might add something to the docstring?

**Comment by galund** [comment]
Yep, docstring fine too, I'm not gonna be precious about that.

(Yes if I see the logic, all the dependencies we'd avoided adding to `requirements.txt` would indeed have to go into a possible `requirements-dev` - let's not go there for now I suppose :-) )

**Pull request merged**
